// services/moodle/syncClass.js
//
// Backend-authoritative sync of ClassSession data so Moodle can DISPLAY live
// class information (subject, teacher, grade, date, time, meeting link,
// status, recording link).
//
// Strictly display-only: Moodle never creates classes or meetings here — the
// StudiesMasters backend (MongoDB) remains the single source of truth and every
// production Google Meet link is generated by services/google.
//
// Imports safely and never throws so a display-sync failure can never take the
// scheduling flow down.
import config from "./config.js";
import { audit } from "./audit.js";
import logger from "../../utils/logger.js";

export const CLASS_SYNC_ACTIONS = {
  CREATED: "CLASS_CREATED",
  UPDATED: "CLASS_UPDATED",
  MEETING_READY: "CLASS_MEETING_READY",
  CANCELLED: "CLASS_CANCELLED",
};

/**
 * Build the Moodle-facing projection of a session (or a plain object shaped
 * like one). Contains only display-safe fields, never attendance PII beyond the
 * link the class itself is entitled to show.
 */
export function toMoodleDisplay(session) {
  const s = session || {};
  return {
    sessionId: String(s._id || s.sessionId || ""),
    subject: s.subject || s.classGroup?.subject || "",
    grade: s.grade || s.classGroup?.grade || "",
    curriculum: s.curriculum || s.classGroup?.curriculum || "",
    teacher: s.teacherName || s.teacher?.fullName || "",
    date: s.date ? new Date(s.date).toISOString() : null,
    startTime: s.startTime || "",
    endTime: s.endTime || "",
    meetingLink: s.meetingLink || "",
    status: s.status || "scheduled",
    meetingStatus: s.meetingStatus || "pending",
    recordingLink: s.recordingLink || "",
  };
}

/**
 * Persist an audit record for a class -> Moodle display sync. Non-throwing.
 * `sessionId` is the ClassSession id and `session` supplies display data.
 */
async function recordClassSync({ sessionId, action = CLASS_SYNC_ACTIONS.UPDATED, session, error = null }) {
  try {
    const payload = toMoodleDisplay(session);
    if (!config.enabled) return { synced: false, reason: "moodle-disabled" };
    if (String(process.env.MOODLE_DRY_RUN || "true") === "true") {
      logger.info(`[MOODLE] OUTBOX class sync (display): ${action} ${sessionId} -> ${JSON.stringify(payload).slice(0, 300)}`);
      return { synced: true, outbox: true, payload };
    }
    await audit({
      action,
      studentRef: null,
      teacherRef: session?.teacher ? session.teacher : null,
      moodleUserId: null,
      outcome: error ? "failure" : "success",
      failure: error ? { message: String(error) } : null,
      detail: payload,
      createdBy: "scheduling",
    }).catch(() => {});
    return { synced: true, payload };
  } catch (err) {
    logger.warn(`[MOODLE] class display sync failed (non-fatal): ${action} ${sessionId}: ${err.message}`);
    return { synced: false, reason: err.message };
  }
}

/** Notify Moodle that a session (with meeting details) should be displayed. */
export async function syncClassSession(session, { action = CLASS_SYNC_ACTIONS.UPDATED, sessionId = null } = {}) {
  const id = sessionId || session?._id || session?.sessionId || "";
  // Ensure the session is populated so display fields (subject, grade, teacher) resolve.
  let populated = session;
  if (session?.classGroup && !session.classGroup.subject) {
    // classGroup is an ObjectId ref, not populated — fetch the populated doc.
    try {
      const ClassSession = (await import("../../models/ClassSession.js")).default;
      const doc = await ClassSession.findById(id)
        .populate("classGroup", "code subject grade curriculum")
        .populate("teacher", "fullName")
        .populate("substituteTeacher", "fullName")
        .lean();
      if (doc) populated = doc;
    } catch { /* fall back to the raw session */ }
  }
  return recordClassSync({ sessionId: String(id), action, session: populated });
}

export default { syncClassSession, toMoodleDisplay, CLASS_SYNC_ACTIONS };