// services/moodle/syncClass.js
//
// Backend-authoritative sync of ClassSession data so Moodle can DISPLAY live
// class information (subject, teacher, grade, date, time, meeting link,
// status, recording link).
//
// Strictly display-only: Moodle never creates classes or meetings here — the
// StudiesMasters backend (MongoDB) remains the single source of truth and every
// production Google Meet link is generated by services/google.
//
// Live push strategy (no custom Moodle plugin required):
//   - Uses STOCK Moodle WS functions: core_calendar_create_calendar_events and
//     core_calendar_delete_calendar_events (updates are emulated as
//     delete + create because this Moodle build does not register an update
//     function).
//   - Events appear in Moodle's native Calendar + Upcoming-events block, with
//     the Meet URL embedded in the event description ("Join Virtual Class").
//   - Course-mapped classes become course events; unmapped ones become site
//     events (visible to everyone) so nothing is ever lost.
//   - The created Moodle event id is stored in MoodleAuditLog.detail so later
//     updates/deletes target the same event (idempotent, no duplicates).
//   - Failures are durable: a `syncClass` SyncJob is enqueued for worker retry.
//   - Display-sync failures NEVER break scheduling (all callers try/catch).
//
// Imports safely and never throws from the scheduling path so a display-sync
// failure can never take the scheduling flow down.
import config from "./config.js";
import { audit } from "./audit.js";
import { callWs } from "./client.js";
import { getCourseIdsFor } from "./courseMapper.js";
import { enqueue } from "./queue.js";
import logger from "../../utils/logger.js";

export const CLASS_SYNC_ACTIONS = {
  CREATED: "CLASS_CREATED",
  UPDATED: "CLASS_UPDATED",
  MEETING_READY: "CLASS_MEETING_READY",
  CANCELLED: "CLASS_CANCELLED",
};

/**
 * Build the Moodle-facing projection of a session (or a plain object shaped
 * like one). Contains only display-safe fields, never attendance PII beyond the
 * link the class itself is entitled to show.
 */
export function toMoodleDisplay(session) {
  const s = session || {};
  return {
    sessionId: String(s._id || s.sessionId || ""),
    subject: s.subject || s.classGroup?.subject || "",
    grade: s.grade || s.classGroup?.grade || "",
    curriculum: s.curriculum || s.classGroup?.curriculum || "",
    teacher: s.teacherName || s.teacher?.fullName || "",
    date: s.date ? new Date(s.date).toISOString() : null,
    startTime: s.startTime || "",
    endTime: s.endTime || "",
    meetingLink: s.meetingLink || "",
    status: s.status || "scheduled",
    meetingStatus: s.meetingStatus || "pending",
    recordingLink: s.recordingLink || "",
  };
}

/**
 * Persist an audit record for a class -> Moodle display sync. Non-throwing.
 * `sessionId` is the ClassSession id and `session` supplies display data.
 *
 * Pipeline (backend still the single source of truth):
 *   1. Build the display projection (toMoodleDisplay).
 *   2. Moodle disabled          -> { synced:false, reason:"moodle-disabled" }.
 *   3. MOODLE_DRY_RUN=true      -> log-only OUTBOX (offline-safe default).
 *   4. WS not configured        -> audit-only outbox (MoodleAuditLog row).
 *   5. Otherwise                -> LIVE push via stock calendar WS, audit the
 *      result, and enqueue a durable retry job on failure.
 */
async function recordClassSync({ sessionId, action = CLASS_SYNC_ACTIONS.UPDATED, session, error = null }) {
  const payload = toMoodleDisplay(session);
  try {
    if (!config.enabled) return { synced: false, reason: "moodle-disabled", payload };
    if (String(process.env.MOODLE_DRY_RUN || "true") === "true") {
      logger.info(`[MOODLE] OUTBOX class sync (display): ${action} ${sessionId} -> ${JSON.stringify(payload).slice(0, 300)}`);
      return { synced: true, outbox: true, payload };
    }
    const live = await pushClassToMoodle({ sessionId: String(sessionId), action, session, payload, error });
    return live;
  } catch (err) {
    logger.warn(`[MOODLE] class display sync failed (non-fatal): ${action} ${sessionId}: ${err.message}`);
    await queueClassSyncRetry({ sessionId: String(sessionId), action, payload, reason: err.message }).catch(() => {});
    return { synced: false, reason: err.message, payload };
  }
}

/** Notify Moodle that a session (with meeting details) should be displayed. */
export async function syncClassSession(session, { action = CLASS_SYNC_ACTIONS.UPDATED, sessionId = null } = {}) {
  const id = sessionId || session?._id || session?.sessionId || "";
  // Ensure the session is populated so display fields (subject, grade, teacher) resolve.
  let populated = session;
  if (session?.classGroup && !session.classGroup.subject) {
    // classGroup is an ObjectId ref, not populated — fetch the populated doc.
    try {
      const ClassSession = (await import("../../models/ClassSession.js")).default;
      const doc = await ClassSession.findById(id)
        .populate("classGroup", "code subject grade curriculum")
        .populate("teacher", "fullName")
        .populate("substituteTeacher", "fullName")
        .lean();
      if (doc) populated = doc;
    } catch { /* fall back to the raw session */ }
  }
  return recordClassSync({ sessionId: String(id), action, session: populated });
}

// ---------------------------------------------------------------------------
// Live push internals (stock Moodle calendar WS — no custom plugin needed)
// ---------------------------------------------------------------------------

const SYNC_JOB_TYPE = "syncClass";

/** Find the most recent Moodle event id we created for this session. */
async function findPriorMoodleEventId(sessionId) {
  try {
    const MoodleAuditLog = (await import("../../models/MoodleAuditLog.js")).default;
    const row = await MoodleAuditLog.findOne({
      action: { $in: [CLASS_SYNC_ACTIONS.CREATED, CLASS_SYNC_ACTIONS.UPDATED, CLASS_SYNC_ACTIONS.MEETING_READY] },
      "detail.sessionId": String(sessionId),
      "detail.moodleEventId": { $ne: null },
    })
      .sort({ createdAt: -1 })
      .select("detail")
      .lean();
    const id = row?.detail?.moodleEventId;
    return Number.isInteger(id) && id > 0 ? id : (Number(id) > 0 ? Number(id) : null);
  } catch { return null; }
}

/** Resolve the Moodle course for this class via CourseMapping (or null for site event). */
async function resolveMoodleCourseId(session) {
  try {
    const group = session?.classGroup && typeof session.classGroup === "object" ? session.classGroup : {};
    const ids = await getCourseIdsFor({
      subjects: group.subject ? [{ name: group.subject }] : [],
      curriculum: group.curriculum || null,
      packageName: null,
      grade: group.grade || null,
    });
    const first = (ids || []).find((n) => Number.isInteger(n) && n > 0);
    return first || null;
  } catch { return null; }
}

/** Local "HH:MM" on a date -> epoch seconds in Africa/Accra (+00:00, no DST). */
function toEpochSeconds(dateLike, hhmm) {
  const d = dateLike ? new Date(dateLike) : new Date();
  const m = String(hhmm || "00:00").match(/^(\d{1,2}):(\d{2})/) || [null, "0", "0"];
  const hh = Math.min(23, parseInt(m[1] || "0", 10));
  const mm = Math.min(59, parseInt(m[2] || "0", 10));
  const y = d.getUTCFullYear();
  const mo = String(d.getUTCMonth() + 1).padStart(2, "0");
  const day = String(d.getUTCDate()).padStart(2, "0");
  // Ghana is UTC+0 year-round, so a plain +00:00 offset is exact.
  return Math.floor(new Date(`${y}-${mo}-${day}T${String(hh).padStart(2, "0")}:${String(mm).padStart(2, "0")}:00+00:00`).getTime() / 1000);
}

/** HTML description shown inside the Moodle calendar event. */
function buildEventDescription(payload) {
  const lines = [
    `<p><strong>${escHtml(payload.subject || "Virtual Class")}${payload.grade ? ` — ${escHtml(payload.grade)}` : ""}</strong></p>`,
    payload.teacher ? `<p>Teacher: ${escHtml(payload.teacher)}</p>` : "",
    payload.date ? `<p>Date: ${escHtml(String(payload.date).slice(0, 10))}${payload.startTime ? ` · ${escHtml(payload.startTime)}–${escHtml(payload.endTime || "")}` : ""}</p>` : "",
    payload.status ? `<p>Status: ${escHtml(payload.status)}${payload.meetingStatus ? ` (${escHtml(payload.meetingStatus)})` : ""}</p>` : "",
  ];
  if (payload.meetingLink) {
    lines.push(`<p><a href="${escAttr(payload.meetingLink)}" target="_blank" rel="noopener"><strong>Join Virtual Class (Google Meet)</strong></a></p>`);
    lines.push(`<p>Meeting link: ${escHtml(payload.meetingLink)}</p>`);
  } else {
    lines.push(`<p><em>Meeting link pending — check back shortly.</em></p>`);
  }
  if (payload.recordingLink) {
    lines.push(`<p><a href="${escAttr(payload.recordingLink)}" target="_blank" rel="noopener">Watch recording</a></p>`);
  }
  lines.push(`<p><small>Source: StudiesMasters (session ${escHtml(payload.sessionId)})</small></p>`);
  return lines.filter(Boolean).join("");
}

function escHtml(v) {
  return String(v ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
function escAttr(v) {
  return String(v ?? "").replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;");
}

/**
 * Push one class to Moodle via stock calendar WS functions.
 * Idempotent: reuses the stored moodleEventId for update/delete.
 */
async function pushClassToMoodle({ sessionId, action, session, payload, error }) {
  const teacherRef = session?.teacher && session.teacher._id ? session.teacher._id : (session?.teacher || null);
  const auditBase = { studentRef: null, teacherRef, moodleUserId: null, createdBy: "scheduling" };

  // WS not configured -> audit-only outbox (previous behaviour, never throws).
  if (!config.wsEnabled || !config.wsToken) {
    await audit({
      ...auditBase, action,
      outcome: error ? "failure" : "success",
      failure: error ? { message: String(error) } : { message: "MOODLE_WS not configured — audit-only outbox" },
      detail: payload,
    }).catch(() => {});
    return { synced: true, outbox: true, reason: "ws-not-configured", payload };
  }

  const priorEventId = await findPriorMoodleEventId(sessionId);

  // Cancellation -> delete the Moodle event we created (if any).
  // core_calendar_delete_calendar_events on this Moodle REQUIRES the "repeat"
  // key inside the event structure (verified live; without it Moodle rejects
  // with "Missing required key in single structure: repeat").
  if (action === CLASS_SYNC_ACTIONS.CANCELLED) {
    if (priorEventId) {
      try {
        await callWs("core_calendar_delete_calendar_events", { "events[0][eventid]": priorEventId, "events[0][repeat]": 0 });
      } catch (wsErr) {
        logger.warn(`[MOODLE] delete calendar event ${priorEventId} failed (non-fatal): ${wsErr.message}`);
      }
    }
    await audit({ ...auditBase, action, outcome: "success", detail: { ...payload, moodleEventId: priorEventId } }).catch(() => {});
    logger.info(`[MOODLE] LIVE class sync: ${action} ${sessionId} (event ${priorEventId || "none"} removed)`);
    return { synced: true, live: true, deleted: Boolean(priorEventId), moodleEventId: priorEventId, payload };
  }

  const courseId = await resolveMoodleCourseId(session);
  const name = `${payload.subject || "Virtual Class"}${payload.grade ? ` — ${payload.grade}` : ""}${payload.teacher ? ` (${payload.teacher})` : ""}`.slice(0, 255);
  const timestart = toEpochSeconds(payload.date, payload.startTime);
  const timeduration = Math.max(0, (toEpochSeconds(payload.date, payload.endTime) - timestart) || 3600);
  const description = buildEventDescription(payload);

  const baseParams = {
    "events[0][name]": name,
    "events[0][description]": description,
    // Moodle's external API validates parameters STRICTLY. Verified live
    // against Moodle 4.5.13 (LMS): the event structure uses the LEGACY key
    // "format" for the description format (NOT "descriptionformat") and has no
    // "uuid" key — unknown keys abort the whole call with
    // "Invalid parameter value detected: Unexpected keys (...) detected".
    "events[0][format]": 1, // 1 = HTML
    "events[0][eventtype]": courseId ? "course" : "site",
    "events[0][timestart]": timestart,
    "events[0][timeduration]": timeduration,
  };
  if (courseId) baseParams["events[0][courseid]"] = courseId;

  // Update path: core_calendar_update_calendar_events is NOT registered on the
  // production Moodle (verified: dml_missing_record_exception on
  // {external_functions}), so an update is emulated with delete + create.
  // Delete requires events[0][repeat] on this Moodle or it is rejected.
  if (priorEventId && action !== CLASS_SYNC_ACTIONS.CREATED) {
    try {
      await callWs("core_calendar_delete_calendar_events", { "events[0][eventid]": priorEventId, "events[0][repeat]": 0 });
      logger.info(`[MOODLE] deleted prior calendar event ${priorEventId} for re-create (${sessionId})`);
    } catch (wsErr) {
      // Non-fatal: the event may already be gone; create below is idempotent
      // enough for display purposes.
      logger.warn(`[MOODLE] delete of prior event ${priorEventId} failed, recreating anyway: ${wsErr.message}`);
    }
  }

  try {
    const res = await callWs("core_calendar_create_calendar_events", baseParams);
    const created = Array.isArray(res?.events) ? res.events[0] : res?.event || null;
    const moodleEventId = Number(created?.id || created?.eventid || res?.eventid || 0) || null;
    await audit({ ...auditBase, action, outcome: "success", detail: { ...payload, moodleEventId, moodleCourseId: courseId } }).catch(() => {});
    logger.info(`[MOODLE] LIVE class sync: ${action} ${sessionId} -> event ${moodleEventId || "?"}`);
    return { synced: true, live: true, created: true, moodleEventId, moodleCourseId: courseId, payload };
  } catch (wsErr) {
    await audit({
      ...auditBase, action, outcome: "failure",
      failure: { message: String(wsErr?.message || wsErr) },
      detail: { ...payload, moodleCourseId: courseId },
    }).catch(() => {});
    // Durable retry — the worker replays this later, scheduling is unaffected.
    await queueClassSyncRetry({ sessionId, action, payload, reason: wsErr?.message || "ws-fault" }).catch(() => {});
    logger.warn(`[MOODLE] LIVE class sync failed (queued for retry): ${action} ${sessionId}: ${wsErr?.message || wsErr}`);
    return { synced: false, live: false, queued: true, reason: String(wsErr?.message || wsErr).slice(0, 300), payload };
  }
}

/** Enqueue a durable `syncClass` job so the worker can replay a failed push. */
async function queueClassSyncRetry({ sessionId, action, payload, reason }) {
  try {
    await enqueue({
      type: SYNC_JOB_TYPE,
      payload: { sessionId: String(sessionId), action, display: payload, note: String(reason || "").slice(0, 300) },
      idempotencyKey: `syncClass:${String(sessionId)}:${action}`,
      maxAttempts: 5,
      backoffMs: 5000,
    });
  } catch { /* queue failure must never break scheduling */ }
}
/**
 * Worker entry point: replay one queued class sync.
 * Exported for worker.js HANDLERS (non-throwing contract of the worker).
 */
export async function replayQueuedClassSync({ sessionId, action }) {
  const ClassSession = (await import("../../models/ClassSession.js")).default;
  const doc = await ClassSession.findById(sessionId)
    .populate("classGroup", "code subject grade curriculum")
    .populate("teacher", "fullName")
    .populate("substituteTeacher", "fullName")
    .lean();
  if (!doc) throw new Error(`ClassSession ${sessionId} not found for Moodle replay`);
  const res = await recordClassSync({ sessionId: String(sessionId), action: action || CLASS_SYNC_ACTIONS.UPDATED, session: doc });
  if (!res.synced) throw new Error(res.reason || "moodle replay failed");
  return res;
}

export default { syncClassSession, toMoodleDisplay, replayQueuedClassSync, CLASS_SYNC_ACTIONS };